networks:
    app-network:
        driver: bridge
volumes:
    app-redis:
        driver: local

services:
    php:
        image: board-way/app
        restart: always
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www'
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - redis
    nginx:
        image: nginx:alpine
        restart: always
        depends_on:
            - php
        ports:
            - "${APP_PORT:-80}:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app-network
    queues:
        image: board-way/app
        restart: always
        entrypoint: 'php /var/www/artisan queue:work --sleep=3 --tries=3'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www'
        networks:
            - app-network
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        restart: always
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'app-redis:/data'
        networks:
            - app-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        restart: always
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_SERVER_PORT: '9601'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
        networks:
            - app-network
