networks:
    app-network:
        driver: bridge
volumes:
    app-redis:
        driver: local

services:
    php:
        image: board-way/app
        restart: always
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www'
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - redis
    nginx:
        image: nginx:alpine
        restart: always
        depends_on:
            - php
        ports:
            - "${APP_PORT:-80}:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app-network
    queues:
        image: board-way/app
        restart: always
        entrypoint: 'php /var/www/artisan queue:work --sleep=3 --tries=3'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www'
        networks:
            - app-network
        depends_on:
            - redis
    redis:
        image: redis/redis-stack:latest
        restart: always
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
            - '8001:8001'
        volumes:
            - 'app-redis:/data'
        networks:
            - app-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    socketio:
        image: board-way/socket-io
        build:
            context: ./docker/socketio
            dockerfile: Dockerfile
        volumes:
            - ./socket-io-server.js:/app/server.js
        restart: always
        depends_on:
            - redis
        ports:
            - "3000:3000"
        networks:
            - app-network
